AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless RPC API

Parameters:
  Stage:
    Type: String
    Description: The stage where the application is running in, e.g., dev, prod.
    Default: dev

Globals:
  Function:
    Runtime: go1.x
    Timeout: 10
    MemorySize: 512

Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      TracingEnabled: true # Enable AWS X-Ray to help debug API requests
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'authorization, content-type'"
  
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api
      CodeUri: dist
      Environment:
        Variables:
          STAGE: !Ref Stage
      Events:
        ApiCall:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: any
