version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    environment: 
      - SERVICES=serverless
      - EDGE_PORT=4566
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566-4584:4566-4584"
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"