name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  cdk-ci:
    name: CDK CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./_cdk
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint && npm run prettier
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: bufbuild/buf-setup-action@v0.6.0
    - uses: arduino/setup-protoc@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install protoc generators
      run: |
        go get github.com/golang/protobuf/protoc-gen-go
        go get github.com/twitchtv/twirp/protoc-gen-twirp

    - name: Run Lint
      run: make lint

    - name: Run Tests
      run: make test

    - name: Run Build
      run: make build
